common: &common
  adapter: postgresql
  username: postgres
  password: nhfychrbgwbz92

development:
  <<: *common
  database: studentime_dev

test:
  <<: *common
  database: studentime_test

production:
  <<: *common
  database: studentime
